name: 构建docker镜像
on:
  # main分支的push操作会触发当前脚本的执行
  push:
    branches: [ main ]

jobs:
  build:
    # 当前脚本是在容器中运行的，对应的镜像是ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    # 检出代码
    - uses: actions/checkout@v2
    - name: Login docker hub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      # 指定login命令登录hub.docker.com，帐号和密码已经在GitHub网页中配置好了
      run: 
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
    - name: Build dockerfile
      # 构建镜像，用buildx可以同时构建X86和ARM架构的镜像，然后推送到hub.docker.com
      run: 
        docker build --output "type=image,push=true" --tag xuefengfeiwu1/myimg:v1 .
